from app.models.auth_token import MagicLinkUse
from app.models.comms import (
    Announcement,
    AnnouncementAudience,
    AnnouncementStatus,
    AuditEvent,
)
from app.models.council import Council, Ward
from app.models.legacy_modules import (
    AdoptionApplication,
    AdoptionStatus,
    Animal,
    AppointmentStatus,
    DAStatus,
    DevelopmentApplication,
    ReportAppointment,
    ReportSignature,
    WasteCollection,
    WaterConsumption,
)
from app.models.payment import (
    Payment,
    PaymentPlan,
    PaymentProvider,
    PaymentStatus,
    PlanStatus,
    WebhookEvent,
)
from app.models.rates import (
    BillingSetting,
    BpayCrn,
    Concession,
    InvoiceStatus,
    Property,
    PropertyOverlay,
    PropertyOwnership,
    PropertyType,
    RateCharge,
    RatesAccount,
    RatesInvoice,
    Valuation,
    WasteEntitlement,
)
from app.models.report import (
    Report,
    ReportAttachment,
    ReportCategory,
    ReportEvent,
    ReportEventKind,
    ReportPriority,
    ReportStatus,
    ReportSubscription,
)
from app.models.team import StaffTeam, StaffTeamMember
from app.models.user import SsoIdentity, TenantSsoConfig, User, UserRole, UserStatus

__all__ = [
    "AdoptionApplication",
    "AdoptionStatus",
    "Animal",
    "Announcement",
    "AnnouncementAudience",
    "AnnouncementStatus",
    "AppointmentStatus",
    "AuditEvent",
    "BillingSetting",
    "DAStatus",
    "DevelopmentApplication",
    "ReportAppointment",
    "ReportSignature",
    "WasteCollection",
    "WaterConsumption",
    "BpayCrn",
    "Concession",
    "Council",
    "InvoiceStatus",
    "MagicLinkUse",
    "Payment",
    "PaymentPlan",
    "PaymentProvider",
    "PaymentStatus",
    "PlanStatus",
    "Property",
    "PropertyOverlay",
    "PropertyOwnership",
    "PropertyType",
    "RateCharge",
    "RatesAccount",
    "RatesInvoice",
    "Report",
    "ReportAttachment",
    "ReportCategory",
    "ReportEvent",
    "ReportEventKind",
    "ReportPriority",
    "ReportStatus",
    "ReportSubscription",
    "SsoIdentity",
    "StaffTeam",
    "StaffTeamMember",
    "TenantSsoConfig",
    "User",
    "UserRole",
    "UserStatus",
    "Valuation",
    "Ward",
    "WasteEntitlement",
    "WebhookEvent",
]
