"""Grant-writing helper — FOSS-only.

Default: template-based draft generator (no external API). For real
LLM assist, wire a local Ollama instance and POST to it from here.
"""
from __future__ import annotations

import textwrap

GRANT_TEMPLATE = """\
# {title}

## Project summary
{summary}

## Background and need
Our community has identified a clear need for this initiative. [Add 2-3
sentences describing the problem you're solving and who's affected. Use
local data where possible — population figures, demographic stats, or
findings from community consultation.]

## Project objectives
1. [Objective 1 — what will be delivered]
2. [Objective 2 — measurable outcome]
3. [Objective 3 — lasting community benefit]

## Approach and methodology
[Describe how you will deliver the project. Break it into 3-4 phases
with timeframes. Identify the team, key partnerships, and the venue or
site if applicable.]

## Budget
Total requested: {amount}

| Item | Cost (AUD) |
| --- | --- |
| [Materials] | [$] |
| [Labour] | [$] |
| [Hire / venue] | [$] |
| [Communications] | [$] |
| [Contingency 10%] | [$] |

## Outcomes and evaluation
[How will you measure success? Numbers attending, surveys, photos,
infrastructure delivered, ongoing program participation.]

## Acknowledgement
We will acknowledge {grant_source} in all promotional materials and
final reporting, per the funder's branding guidelines.

---
Generated by Assembly grant-helper template. Edit freely; council
grants officer can review before submission.
"""


def draft(*, title: str, summary: str, requested_amount_cents: int | None,
          grant_name: str | None) -> dict[str, str]:
    amount = (
        f"AUD ${requested_amount_cents / 100:,.2f}"
        if requested_amount_cents
        else "[amount]"
    )
    text = GRANT_TEMPLATE.format(
        title=title,
        summary=textwrap.fill(summary, width=80),
        amount=amount,
        grant_source=grant_name or "council grants program",
    )
    return {"draft_markdown": text, "provider": "local-template"}
